DROP TABLE IF EXISTS MEMBER CASCADE;
CREATE TABLE MEMBER
(
    id        UUID,
    firstname VARCHAR(100) NOT NULL,
    lastname  VARCHAR(100) NOT NULL,
    email     VARCHAR(100) NOT NULL,
    password  VARCHAR(100) NOT NULL,
    isAdmin   BOOLEAN      NOT NULL DEFAULT FALSE,

    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS PLACE CASCADE;
CREATE TABLE PLACE
(
    id       UUID,
    location VARCHAR(100) NOT NULL,

    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS BOOKING CASCADE;
CREATE TABLE BOOKING
(
    id         UUID,
    member_id  UUID,
    place_id   UUID,
    startDate  TIMESTAMP NOT NULL,
    endDate    TIMESTAMP NOT NULL,
    isAccepted BOOLEAN   NOT NULL DEFAULT FALSE,

    PRIMARY KEY (id),
    FOREIGN KEY (member_id) REFERENCES MEMBER (id),
    FOREIGN KEY (place_id) REFERENCES PLACE (id)
);

